# Generated by Django 2.0.5 on 2018-05-04 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
            ],
            options={
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=16, verbose_name='proxy')),
                ('avg_resp_proxy', models.CharField(max_length=32, verbose_name='avg_resp_proxy')),
                ('avg_avail_proxy', models.CharField(max_length=32, verbose_name='Average available proxy')),
                ('avg_resp_direct', models.CharField(max_length=32, verbose_name='avg_resp_direct')),
                ('avg_avail_direct', models.CharField(max_length=32, verbose_name='Average available direct')),
                ('date', models.DateField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
